def from_p_e_iota_to_consts(p: float, e: float, iota: float, M: float, a: float) -> OrbitConstants:
    ...
def from_consts_to_p_e_iota(E: float, Lz: float, Q: float, M: float, a: float) -> (p,e,iota):
    ...
